### ISSUE TITLE
download_dataset doesn't work as expected on my CHPC system.

### ISSUE THREAD

**Issue by leannmlindsey** [ML-Bioinfo-CEITEC/genomic_benchmarks#38]
I was able to get download_dataset to work as expected on my macbook pro but when I try to use it on my university's CHPC system I get this error.  

Do you have any idea what could be causing this? I am trying to repeat the experiments on the HyenaDNA paper and their code depends upon this function working properly.

(p100_hyena-dna) [u1323098@kp359:test_dir]$ python
Python 3.8.18 | packaged by conda-forge | (default, Oct 10 2023, 15:44:36) 
[GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from genomic_benchmarks.data_check import list_datasets
>>> list_datasets()
['drosophila_enhancers_stark', 'dummy_mouse_enhancers_ensembl', 'human_ensembl_regulatory', 'demo_coding_vs_intergenomic_seqs', 'demo_human_or_worm', 'human_nontata_promoters', 'human_enhancers_ensembl', 'human_enhancers_cohn', 'human_ocr_ensembl']
>>> from genomic_benchmarks.loc2seq import download_dataset
>>> download_dataset("human_nontata_promoters", version=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/uufs/chpc.utah.edu/common/home/u1323098/software/pkg/miniconda3/envs/p100_hyena-dna/lib/python3.8/site-packages/genomic_benchmarks/loc2seq/loc2seq.py", line 55, in download_dataset
    return download_from_cloud_cache((dataset_name, version), Path(dest_path) / dataset_name)
  File "/uufs/chpc.utah.edu/common/home/u1323098/software/pkg/miniconda3/envs/p100_hyena-dna/lib/python3.8/site-packages/genomic_benchmarks/loc2seq/cloud_caching.py", line 32, in download_from_cloud_cache
    gdown.download(
  File "/uufs/chpc.utah.edu/common/home/u1323098/software/pkg/miniconda3/envs/p100_hyena-dna/lib/python3.8/site-packages/gdown/download.py", line 259, in download
    filename_from_url = m.groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by davidboening** [comment]
I had the same problem today, updating `gdown` fixed the issue:
```pip install --upgrade gdown```
I'm guessing this is due to some changes in the Google Drive API.

**Comment by katarinagresova** [comment]
Dear @leannmlindsey and @davidboening, you are correct, there were problems with `gdown` package. Therefore we have decided to move. cache to Zenodo, see PR https://github.com/ML-Bioinfo-CEITEC/genomic_benchmarks/pull/42.

To use new cache, update the package to version `1.0.0`
